version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 8001:8080
    volumes:
      - ${SOURCE_DIR}/data:/data
      - ${SOURCE_DIR}/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always