---
- name: Linux patch cycle
  when: ansible_os_family != "Windows"
  block:
    - name: Set timezone to America/New_York
      community.general.timezone:
        name: America/New_York
      become: true

    - name: Check if line exists in sudoers file
      command: grep -q "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL" /etc/sudoers
      register: grep_result
      changed_when: false
      ignore_errors: yes
      bcome: true

    - name: Add ansible user to sudoers file
      lineinfile:
        dest: /etc/sudoers
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
      when: grep_result.rc != 0
      become: true

    - name: Upgrade all rpm packages
      yum:
        name: '*'
        state: latest
      become: true
      when: >
        ansible_distribution == "Rocky" or
        ansible_os_family == "RedHat"
      register: rpm_result

    - name: Upgrade all apt packages
      apt:
        update_cache: true
        name: "*"
        state: latest
      become: true
      when: ansible_distribution == "Ubuntu"
      register: apt_result

    - name: Upgrade all FreeBSD packages
      shell: |
        pkg-static update -fq
      become: true
      when: ansible_distribution == "FreeBSD"
      register: bsd_result

    - name: Reboot
      become: true
      reboot:

- name: Windows patch cycle
  when: ansible_os_family == "Windows"
  vars:
  block:

    - name: Create C:\Temp directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Install chocolatey packages
      win_chocolatey:
        name: 
          - vim
        state: present

    - name: Upgrade installed packages
      win_chocolatey:
        name: all
        state: latest

    - name: Install Windows updates
      win_updates:
        category_names: "{{ windows_update_categories }}"
        state: installed
      register: update_result

    - name: Reboot the server if necessary
      win_reboot:
      when: update_result.reboot_required
