---
- name: Install docker via deb
  include_tasks: install_deb.yml
  when: ansible_os_family == "Debian"

- name: Install docker via rpm
  include_tasks: install_rpm.yml
  when: ansible_os_family == "RedHat"

- name: Configure docker
  include_tasks: config.yml