---
- name: Install docker via yum
  when: >
    ansible_distribution == "Rocky" or
    ansible_os_family == "RedHat"
  block:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      become: yes

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: latest
      become: yes

    - name: Add Docker repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      become: yes

    - name: Install Docker engine
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      become: yes

    - name: Create docker group
      group:
        name: docker
        state: present
      become: yes

    - name: Add ansible user to docker group
      user: 
        name: ansible
        group: docker
      become: yes

    - name: Start and enable Docker services
      systemd:
        name: docker
        state: started
        enabled: true
      become: yes

    - name: Change permissions on docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'
      become: yes

- name: Create /app/docker directory
  file:
    path: /app/docker
    state: directory
    owner: ansible
    mode: '0755'
  become: yes