version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "${SERVER_PORT}:25565"
    environment:
      TZ: "${TZ}"
      GUI: "false"
      VERSION: "${VERSION}"
      EULA: "TRUE"
      MEMORY: "${MEMORY}"
      SIMULATION_DISTANCE: "${SIMULATION_DISTANCE}"
      ENABLE_COMMAND_BLOCK: "${ENABLE_COMMAND_BLOCK}"
      ALLOW_NETHER: "${ALLOW_NETHER}"
      ALLOW_FLIGHT: "${ALLOW_FLIGHT}"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "${ANNOUNCE_PLAYER_ACHIEVEMENTS}"
      MOTD: "${SERVER_NAME}"
      DIFFICULTY: "${DIFFICULTY}"
      FORCE_GAMEMODE: "${FORCE_GAMEMODE}"
      SNOOPER_ENABLED: "${SNOOPER_ENABLED}"
      LEVEL: "world"
      HARDCORE: "${HARDCORE}"
      SEED: "${SEED}"
      GENERATE_STRUCTURES: "${GENERATE_STRUCTURES}"
      MAX_WORLD_SIZE: "${MAX_WORLD_SIZE}"
      MAX_TICK_TIME: 60000
      MAX_BUILD_HEIGHT: "${MAX_BUILD_HEIGHT}"
      MAX_PLAYERS: "${MAX_PLAYERS}"
      SPAWN_ANIMALS: "${SPAWN_ANIMALS}"
      SPAWN_MONSTERS: "${SPAWN_MONSTERS}"
      SPAWN_NPCS: "${SPAWN_NPCS}"
      SPAWN_PROTECTION: "${SPAWN_PROTECTION}"
      VIEW_DISTANCE: "${VIEW_DISTANCE}"
      MODE: "${MODE}"
      PVP: "${PVP}"
      LEVEL_TYPE: "${LEVEL_TYPE}"
      ENABLE_RCON: "${ENABLE_RCON}"
      ENABLE_WHITELIST: "${ENABLE_WHITELIST}"
      ENFORCE_WHITELIST: "${ENFORCE_WHITELIST}"
      SERVER_NAME: "${SERVER_NAME}"
      SERVER_PORT: "${SERVER_PORT}"
      QUERY_PORT: "${QUERY_PORT}"
      WHITELIST: "${WHITELIST}"
      OPS: "${OPS}"
    volumes:
      - "${SOURCE_DIR}:/data"