---
- name: Create /app/semaphore directory
  file:
    path: /app/semaphore
    state: directory
    owner: ansible
    mode: '0755'
  become: yes

- name: Copy Docker Compose file with variables
  template:
    src: docker-compose.yml.j2
    dest: /app/semaphore/docker-compose.yml

- name: Start docker compose
  shell: 
    cmd: docker compose up -d
    chdir: /app/semaphore
  register: docker_output

- debug:
    msg: "{{ docker_output.stdout }}"