---
- name: Join Windows VM to Active Directory domain
  win_domain_membership:
    dns_domain_name: "{{ ad_domain_name }}"
    domain_admin_user: "{{ ad_domain_admin }}"
    domain_admin_password: "{{ ad_domain_password }}"
    state: domain
  register: domain_join

- name: Reboot if domain join requires
  win_reboot:
  when: domain_join.reboot_required