---
- name: Patch Cycle
  hosts: all,!pfsense,!ansible-c01
  serial: 1
  ignore_errors: true
  ignore_unreachable: true
  roles:
    - patch_cycle
  tags: 
    - patch_cycle

- name: Shutdown Cycle
  hosts: all,!pfsense,!ansible-c01
  serial: 1
  roles:
    - shutdown_cycle
  tags:
    - shutdown_cycle