---
- name: Patch Cycle
  hosts: all,!pfsense,!ansible-c01
  serial: 1
  ignore_errors: true
  ignore_unreachable: true
  roles:
    - patch_cycle
  tags: 
    - patch_cycle

- name: Shutdown Cycle
  hosts: all,!pfsense,!ansible-c01
  serial: 1
  roles:
    - shutdown_cycle
  tags:
    - shutdown_cycle

- name: Respond Cycle
  hosts: all
  roles:
    - respond
  tags:
    - respond

- name: Minecraft Backup Cycle
  hosts: port-p01,localhost
  vars:
    mc_server: port-p01
    backup_server: localhost
  roles:
    - mc-backup
  tags:
    - mc-backup