---
- name: Add port forwarding rule for MS RDP
  pfsensible.core.pfsense_nat_port_forward:
    descr: 'admin-rdp'
    interface: wan
    source: any
    destination: 10.1.21.2:3389
    target: 10.1.22.4:3389
    associated_rule: pass
    state: present
  become: true