---
- name: Inventory facts
  debug:
    msg:
      - "Hostname: {{ inventory_hostname }}"
      - "Date: {{ ansible_date_time.date }}"
      - "Time: {{ ansible_date_time.time }}"
      - "OS Family: {{ ansible_os_family }}"
      - "OS Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"
    